// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgPeople = function() { };
LoadImgPeople.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgPeople.index = 0;
		LoadImgPeople.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgPeople.index = (LoadImgPeople.index - 1 + LoadImgPeople.images.length) % LoadImgPeople.images.length;
		LoadImgPeople.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgPeople.index = (LoadImgPeople.index + 1) % LoadImgPeople.images.length;
		LoadImgPeople.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgPeople.index = LoadImgPeople.images.length - 1;
		LoadImgPeople.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgPeople.index = (LoadImgPeople.index - 1 + LoadImgPeople.images.length) % LoadImgPeople.images.length;
			LoadImgPeople.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgPeople.index = (LoadImgPeople.index + 1) % LoadImgPeople.images.length;
			LoadImgPeople.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgPeople.index = LoadImgPeople.images.length - 1;
			LoadImgPeople.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgPeople.index = 0;
			LoadImgPeople.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	artwork.addEventListener("touchstart",function(e) {
		LoadImgPeople.startX = e.touches[0].clientX;
		LoadImgPeople.dragging = true;
	});
	artwork.addEventListener("touchmove",function(e) {
		if(LoadImgPeople.dragging) {
			LoadImgPeople.endX = e.touches[0].clientX;
		}
	});
	artwork.addEventListener("touchend",function(e) {
		if(LoadImgPeople.dragging) {
			LoadImgPeople.dragging = false;
			LoadImgPeople.handleSwipe(artwork,title);
		}
	});
	artwork.addEventListener("mousedown",function(e) {
		LoadImgPeople.startX = e.clientX;
		LoadImgPeople.dragging = true;
	});
	window.document.addEventListener("mousemove",function(e) {
		if(LoadImgPeople.dragging) {
			LoadImgPeople.endX = e.clientX;
		}
	});
	window.document.addEventListener("mouseup",function(e) {
		if(LoadImgPeople.dragging) {
			LoadImgPeople.dragging = false;
			LoadImgPeople.handleSwipe(artwork,title);
		}
	});
	LoadImgPeople.fadeUpdate(artwork,title);
};
LoadImgPeople.handleSwipe = function(artwork,title) {
	var diff = LoadImgPeople.endX - LoadImgPeople.startX;
	var threshold = 50;
	if(Math.abs(diff) < threshold) {
		return;
	}
	if(diff < 0) {
		LoadImgPeople.index = (LoadImgPeople.index + 1) % LoadImgPeople.images.length;
	} else {
		LoadImgPeople.index = (LoadImgPeople.index - 1 + LoadImgPeople.images.length) % LoadImgPeople.images.length;
	}
	LoadImgPeople.fadeUpdate(artwork,title);
};
LoadImgPeople.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgPeople.images[LoadImgPeople.index].url;
		title.innerText = LoadImgPeople.images[LoadImgPeople.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgPeople.images = [{ url : "../img/onTheBeach.jpg", title : "Beach Scene"},{ url : "../img/nicOnTheBeach.jpg", title : "Nicola - Beach Scene"},{ url : "../img/andyOnTheBeach.jpg", title : "Andy - Beach Scene"},{ url : "../img/family.jpg", title : "Family - Beach Scene"},{ url : "../img/girl_mystery.jpg", title : "Girl - Mystery"}];
LoadImgPeople.index = 0;
LoadImgPeople.startX = 0;
LoadImgPeople.endX = 0;
LoadImgPeople.dragging = false;
LoadImgPeople.main();
})({});
