// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgCat = function() { };
LoadImgCat.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgCat.index = 0;
		LoadImgCat.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgCat.index = (LoadImgCat.index - 1 + LoadImgCat.images.length) % LoadImgCat.images.length;
		LoadImgCat.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgCat.index = (LoadImgCat.index + 1) % LoadImgCat.images.length;
		LoadImgCat.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgCat.index = LoadImgCat.images.length - 1;
		LoadImgCat.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgCat.index = (LoadImgCat.index - 1 + LoadImgCat.images.length) % LoadImgCat.images.length;
			LoadImgCat.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgCat.index = (LoadImgCat.index + 1) % LoadImgCat.images.length;
			LoadImgCat.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgCat.index = LoadImgCat.images.length - 1;
			LoadImgCat.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgCat.index = 0;
			LoadImgCat.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	LoadImgCat.fadeUpdate(artwork,title);
};
LoadImgCat.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgCat.images[LoadImgCat.index].url;
		title.innerText = LoadImgCat.images[LoadImgCat.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgCat.images = [{ url : "../img/oscar.jpg", title : "Oscar"},{ url : "../img/rosie.jpg", title : "Rosie"}];
LoadImgCat.index = 0;
LoadImgCat.main();
})({});
