// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgPalette = function() { };
LoadImgPalette.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgPalette.index = 0;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgPalette.index = (LoadImgPalette.index - 1 + LoadImgPalette.images.length) % LoadImgPalette.images.length;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgPalette.index = (LoadImgPalette.index + 1) % LoadImgPalette.images.length;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgPalette.index = LoadImgPalette.images.length - 1;
		LoadImgPalette.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgPalette.index = (LoadImgPalette.index - 1 + LoadImgPalette.images.length) % LoadImgPalette.images.length;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgPalette.index = (LoadImgPalette.index + 1) % LoadImgPalette.images.length;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgPalette.index = LoadImgPalette.images.length - 1;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgPalette.index = 0;
			LoadImgPalette.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	LoadImgPalette.fadeUpdate(artwork,title);
};
LoadImgPalette.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgPalette.images[LoadImgPalette.index].url;
		title.innerText = LoadImgPalette.images[LoadImgPalette.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgPalette.images = [{ url : "../img/boat.jpg", title : "Boat"},{ url : "../img/seascape.jpg", title : "Sea Scene"},{ url : "../img/jellyfish.jpg", title : "Jelly Fish"},{ url : "../img/octopus.jpg", title : "Octopus"},{ url : "../img/otter.jpg", title : "Otter"},{ url : "../img/penguin.jpg", title : "Penguin"},{ url : "../img/tortoise.jpg", title : "Tortoise"},{ url : "../img/turtle.jpg", title : "Turtle"}];
LoadImgPalette.index = 0;
LoadImgPalette.main();
})({});
