// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgDog = function() { };
LoadImgDog.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgDog.index = 0;
		LoadImgDog.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgDog.index = (LoadImgDog.index - 1 + LoadImgDog.images.length) % LoadImgDog.images.length;
		LoadImgDog.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgDog.index = (LoadImgDog.index + 1) % LoadImgDog.images.length;
		LoadImgDog.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgDog.index = LoadImgDog.images.length - 1;
		LoadImgDog.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgDog.index = (LoadImgDog.index - 1 + LoadImgDog.images.length) % LoadImgDog.images.length;
			LoadImgDog.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgDog.index = (LoadImgDog.index + 1) % LoadImgDog.images.length;
			LoadImgDog.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgDog.index = LoadImgDog.images.length - 1;
			LoadImgDog.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgDog.index = 0;
			LoadImgDog.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	artwork.addEventListener("touchstart",function(e) {
		LoadImgDog.startX = e.touches[0].clientX;
		LoadImgDog.dragging = true;
	});
	artwork.addEventListener("touchmove",function(e) {
		if(LoadImgDog.dragging) {
			LoadImgDog.endX = e.touches[0].clientX;
		}
	});
	artwork.addEventListener("touchend",function(e) {
		if(LoadImgDog.dragging) {
			LoadImgDog.dragging = false;
			LoadImgDog.handleSwipe(artwork,title);
		}
	});
	artwork.addEventListener("mousedown",function(e) {
		LoadImgDog.startX = e.clientX;
		LoadImgDog.dragging = true;
	});
	window.document.addEventListener("mousemove",function(e) {
		if(LoadImgDog.dragging) {
			LoadImgDog.endX = e.clientX;
		}
	});
	window.document.addEventListener("mouseup",function(e) {
		if(LoadImgDog.dragging) {
			LoadImgDog.dragging = false;
			LoadImgDog.handleSwipe(artwork,title);
		}
	});
	LoadImgDog.fadeUpdate(artwork,title);
};
LoadImgDog.handleSwipe = function(artwork,title) {
	var diff = LoadImgDog.endX - LoadImgDog.startX;
	var threshold = 50;
	if(Math.abs(diff) < threshold) {
		return;
	}
	if(diff < 0) {
		LoadImgDog.index = (LoadImgDog.index + 1) % LoadImgDog.images.length;
	} else {
		LoadImgDog.index = (LoadImgDog.index - 1 + LoadImgDog.images.length) % LoadImgDog.images.length;
	}
	LoadImgDog.fadeUpdate(artwork,title);
};
LoadImgDog.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgDog.images[LoadImgDog.index].url;
		title.innerText = LoadImgDog.images[LoadImgDog.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgDog.images = [{ url : "../img/bailey-playing.jpg", title : "Bailey Playing"},{ url : "../img/bailey.jpg", title : "Bailey"},{ url : "../img/dog.jpg", title : "Dog - 1"},{ url : "../img/dog1.jpg", title : "Dog - 2"},{ url : "../img/dog2.jpg", title : "Dog - 3"},{ url : "../img/dog3.jpg", title : "Dog - 4"},{ url : "../img/dog4.jpg", title : "Dog - 5"},{ url : "../img/dog5.jpg", title : "Dog - 6"},{ url : "../img/dog6.jpg", title : "Dog - 7"},{ url : "../img/dog7.jpg", title : "Dog - 8"},{ url : "../img/oscar.jpg", title : "Oscar"},{ url : "../img/rosie.jpg", title : "Rosie"}];
LoadImgDog.index = 0;
LoadImgDog.startX = 0;
LoadImgDog.endX = 0;
LoadImgDog.dragging = false;
LoadImgDog.main();
})({});
