// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgFarm = function() { };
LoadImgFarm.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgFarm.index = 0;
		LoadImgFarm.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgFarm.index = (LoadImgFarm.index - 1 + LoadImgFarm.images.length) % LoadImgFarm.images.length;
		LoadImgFarm.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgFarm.index = (LoadImgFarm.index + 1) % LoadImgFarm.images.length;
		LoadImgFarm.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgFarm.index = LoadImgFarm.images.length - 1;
		LoadImgFarm.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgFarm.index = (LoadImgFarm.index - 1 + LoadImgFarm.images.length) % LoadImgFarm.images.length;
			LoadImgFarm.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgFarm.index = (LoadImgFarm.index + 1) % LoadImgFarm.images.length;
			LoadImgFarm.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgFarm.index = LoadImgFarm.images.length - 1;
			LoadImgFarm.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgFarm.index = 0;
			LoadImgFarm.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	artwork.addEventListener("touchstart",function(e) {
		LoadImgFarm.startX = e.touches[0].clientX;
		LoadImgFarm.dragging = true;
	});
	artwork.addEventListener("touchmove",function(e) {
		if(LoadImgFarm.dragging) {
			LoadImgFarm.endX = e.touches[0].clientX;
		}
	});
	artwork.addEventListener("touchend",function(e) {
		if(LoadImgFarm.dragging) {
			LoadImgFarm.dragging = false;
			LoadImgFarm.handleSwipe(artwork,title);
		}
	});
	artwork.addEventListener("mousedown",function(e) {
		LoadImgFarm.startX = e.clientX;
		LoadImgFarm.dragging = true;
	});
	window.document.addEventListener("mousemove",function(e) {
		if(LoadImgFarm.dragging) {
			LoadImgFarm.endX = e.clientX;
		}
	});
	window.document.addEventListener("mouseup",function(e) {
		if(LoadImgFarm.dragging) {
			LoadImgFarm.dragging = false;
			LoadImgFarm.handleSwipe(artwork,title);
		}
	});
	LoadImgFarm.fadeUpdate(artwork,title);
};
LoadImgFarm.handleSwipe = function(artwork,title) {
	var diff = LoadImgFarm.endX - LoadImgFarm.startX;
	var threshold = 50;
	if(Math.abs(diff) < threshold) {
		return;
	}
	if(diff < 0) {
		LoadImgFarm.index = (LoadImgFarm.index + 1) % LoadImgFarm.images.length;
	} else {
		LoadImgFarm.index = (LoadImgFarm.index - 1 + LoadImgFarm.images.length) % LoadImgFarm.images.length;
	}
	LoadImgFarm.fadeUpdate(artwork,title);
};
LoadImgFarm.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgFarm.images[LoadImgFarm.index].url;
		title.innerText = LoadImgFarm.images[LoadImgFarm.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgFarm.images = [{ url : "../img/cow.jpg", title : "Cow - 1"},{ url : "../img/cow1.jpg", title : "Cow - 2"},{ url : "../img/donkey.jpg", title : "Donkey - 1"},{ url : "../img/donkey1.jpg", title : "Donkey - 2"},{ url : "../img/donkey2.jpg", title : "Donkey - 3"},{ url : "../img/donkey3.jpg", title : "Donkey - 4"},{ url : "../img/pig.jpg", title : "Pig"},{ url : "../img/pigs.jpg", title : "Pigs"}];
LoadImgFarm.index = 0;
LoadImgFarm.startX = 0;
LoadImgFarm.endX = 0;
LoadImgFarm.dragging = false;
LoadImgFarm.main();
})({});
