// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgTiger = function() { };
LoadImgTiger.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgTiger.index = 0;
		LoadImgTiger.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgTiger.index = (LoadImgTiger.index - 1 + LoadImgTiger.images.length) % LoadImgTiger.images.length;
		LoadImgTiger.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgTiger.index = (LoadImgTiger.index + 1) % LoadImgTiger.images.length;
		LoadImgTiger.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgTiger.index = LoadImgTiger.images.length - 1;
		LoadImgTiger.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgTiger.index = (LoadImgTiger.index - 1 + LoadImgTiger.images.length) % LoadImgTiger.images.length;
			LoadImgTiger.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgTiger.index = (LoadImgTiger.index + 1) % LoadImgTiger.images.length;
			LoadImgTiger.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgTiger.index = LoadImgTiger.images.length - 1;
			LoadImgTiger.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgTiger.index = 0;
			LoadImgTiger.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	LoadImgTiger.fadeUpdate(artwork,title);
};
LoadImgTiger.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgTiger.images[LoadImgTiger.index].url;
		title.innerText = LoadImgTiger.images[LoadImgTiger.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgTiger.images = [{ url : "../img/cheetah.jpg", title : "Cheetah"},{ url : "../img/chimp.jpg", title : "Chimpanzee"},{ url : "../img/elephant.jpg", title : "Elephant's Stare"},{ url : "../img/elephant-2.jpg", title : "Elephant Running"},{ url : "../img/giraffe.jpg", title : "Giraffe"},{ url : "../img/lion.jpg", title : "Lion"},{ url : "../img/rhino.jpg", title : "Rhino's Stare"},{ url : "../img/rhino-2.jpg", title : "Rhino Running"},{ url : "../img/tiger.jpg", title : "Friendly Tiger"},{ url : "../img/tiger-2.jpg", title : "Fierce Tiger"}];
LoadImgTiger.index = 0;
LoadImgTiger.main();
})({});
