// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImgHorse = function() { };
LoadImgHorse.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImgHorse.index = 0;
		LoadImgHorse.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImgHorse.index = (LoadImgHorse.index - 1 + LoadImgHorse.images.length) % LoadImgHorse.images.length;
		LoadImgHorse.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImgHorse.index = (LoadImgHorse.index + 1) % LoadImgHorse.images.length;
		LoadImgHorse.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImgHorse.index = LoadImgHorse.images.length - 1;
		LoadImgHorse.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImgHorse.index = (LoadImgHorse.index - 1 + LoadImgHorse.images.length) % LoadImgHorse.images.length;
			LoadImgHorse.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImgHorse.index = (LoadImgHorse.index + 1) % LoadImgHorse.images.length;
			LoadImgHorse.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImgHorse.index = LoadImgHorse.images.length - 1;
			LoadImgHorse.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImgHorse.index = 0;
			LoadImgHorse.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	LoadImgHorse.fadeUpdate(artwork,title);
};
LoadImgHorse.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImgHorse.images[LoadImgHorse.index].url;
		title.innerText = LoadImgHorse.images[LoadImgHorse.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImgHorse.images = [{ url : "../img/horse1.jpg", title : "Horse - 1"},{ url : "../img/horse2.jpg", title : "Horse - 2"},{ url : "../img/horse3.jpg", title : "Horse - 3"},{ url : "../img/horse4.jpg", title : "Horse - 4"},{ url : "../img/horse5.jpg", title : "Horse - 5"},{ url : "../img/horse6.jpg", title : "Horse - 6"},{ url : "../img/horse7.jpg", title : "Horse - 7"},{ url : "../img/horse8.jpg", title : "Horse - 8"},{ url : "../img/horse9.jpg", title : "Horse - 9"},{ url : "../img/horse10.jpg", title : "Horse - 10"},{ url : "../img/horse11.jpg", title : "Horse - 11"},{ url : "../img/horse12.jpg", title : "Horse - 12"},{ url : "../img/horse13.jpg", title : "Horse - 13"},{ url : "../img/horse14.jpg", title : "Horse - 14"}];
LoadImgHorse.index = 0;
LoadImgHorse.main();
})({});
