// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var LoadImg = function() { };
LoadImg.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	btn1.onclick = function(_) {
		LoadImg.index = 0;
		LoadImg.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		LoadImg.index = (LoadImg.index - 1 + LoadImg.images.length) % LoadImg.images.length;
		LoadImg.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		LoadImg.index = (LoadImg.index + 1) % LoadImg.images.length;
		LoadImg.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		LoadImg.index = LoadImg.images.length - 1;
		LoadImg.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			LoadImg.index = (LoadImg.index - 1 + LoadImg.images.length) % LoadImg.images.length;
			LoadImg.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			LoadImg.index = (LoadImg.index + 1) % LoadImg.images.length;
			LoadImg.fadeUpdate(artwork,title);
			break;
		case "End":
			LoadImg.index = LoadImg.images.length - 1;
			LoadImg.fadeUpdate(artwork,title);
			break;
		case "Home":
			LoadImg.index = 0;
			LoadImg.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	LoadImg.fadeUpdate(artwork,title);
};
LoadImg.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = LoadImg.images[LoadImg.index].url;
		title.innerText = LoadImg.images[LoadImg.index].title;
		artwork.onload = function(_) {
			var w = artwork.naturalWidth;
			var h = artwork.naturalHeight;
			if(h > 2 * w) {
				artwork.style.width = "auto";
				artwork.style.height = "600px";
			} else {
				artwork.style.width = "88%";
				artwork.style.height = "auto";
			}
		};
		artwork.classList.remove("fade-out");
	},300);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
LoadImg.images = [{ url : "img/bailey-playing.jpg", title : "Bailey at Play"},{ url : "img/cheetah.jpg", title : "Cheetah"},{ url : "img/chimp.jpg", title : "Chimpanzee"},{ url : "img/elephant.jpg", title : "Elephant's Stare"},{ url : "img/elephant-2.jpg", title : "Elephant Running"},{ url : "img/giraffe.jpg", title : "Giraffe"},{ url : "img/lion.jpg", title : "Lion"},{ url : "img/rhino.jpg", title : "Rhino's Stare"},{ url : "img/rhino-2.jpg", title : "Rhino Running"},{ url : "img/tiger.jpg", title : "Friendly Tiger"},{ url : "img/tiger-2.jpg", title : "Fierce Tiger"}];
LoadImg.index = 0;
LoadImg.main();
})({});
