// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var artwork = window.document.getElementById("artwork");
	var title = window.document.getElementById("title");
	var btn1 = window.document.getElementById("btn1");
	var btn2 = window.document.getElementById("btn2");
	var btn3 = window.document.getElementById("btn3");
	var btn4 = window.document.getElementById("btn4");
	Main.preloadImages();
	btn1.onclick = function(_) {
		Main.index = 0;
		Main.fadeUpdate(artwork,title);
	};
	btn2.onclick = function(_) {
		Main.index = (Main.index - 1 + Main.images.length) % Main.images.length;
		Main.fadeUpdate(artwork,title);
	};
	btn3.onclick = function(_) {
		Main.index = (Main.index + 1) % Main.images.length;
		Main.fadeUpdate(artwork,title);
	};
	btn4.onclick = function(_) {
		Main.index = Main.images.length - 1;
		Main.fadeUpdate(artwork,title);
	};
	window.document.onkeydown = function(e) {
		switch(e.key) {
		case "ArrowLeft":
			Main.index = (Main.index - 1 + Main.images.length) % Main.images.length;
			Main.fadeUpdate(artwork,title);
			break;
		case "ArrowRight":
			Main.index = (Main.index + 1) % Main.images.length;
			Main.fadeUpdate(artwork,title);
			break;
		case "End":
			Main.index = Main.images.length - 1;
			Main.fadeUpdate(artwork,title);
			break;
		case "Home":
			Main.index = 0;
			Main.fadeUpdate(artwork,title);
			break;
		default:
		}
	};
	artwork.addEventListener("touchstart",function(e) {
		Main.touchStartX = e.touches[0].clientX;
		Main.touchStartTime = window.performance.now();
	});
	artwork.addEventListener("touchend",function(e) {
		Main.touchEndX = e.changedTouches[0].clientX;
		Main.touchEndTime = window.performance.now();
		Main.handleSwipe(artwork,title);
	});
	Main.fadeUpdate(artwork,title);
};
Main.handleSwipe = function(artwork,title) {
	var dx = Main.touchEndX - Main.touchStartX;
	var dt = Main.touchEndTime - Main.touchStartTime;
	var velocity = Math.abs(dx) / dt;
	if(velocity > Main.minSwipeVelocity) {
		if(dx < 0) {
			Main.index = (Main.index + 1) % Main.images.length;
		} else {
			Main.index = (Main.index - 1 + Main.images.length) % Main.images.length;
		}
		Main.fadeUpdate(artwork,title);
		return;
	}
	if(Math.abs(dx) > Main.minSwipeDistance) {
		if(dx < 0) {
			Main.index = (Main.index + 1) % Main.images.length;
		} else {
			Main.index = (Main.index - 1 + Main.images.length) % Main.images.length;
		}
		Main.fadeUpdate(artwork,title);
	}
};
Main.fadeUpdate = function(artwork,title) {
	artwork.classList.add("fade-out");
	window.setTimeout(function() {
		artwork.src = Main.images[Main.index].url;
		title.innerText = Main.images[Main.index].title;
		artwork.classList.remove("fade-out");
		Main.preloadAround(Main.index);
	},300);
};
Main.preloadImages = function() {
	var _g = 0;
	var _g1 = Main.images;
	while(_g < _g1.length) {
		var img = _g1[_g];
		++_g;
		var i = new Image();
		i.src = img.url;
		Main.preloaded.push(i);
	}
};
Main.preloadAround = function(i) {
	var next = (i + 1) % Main.images.length;
	var prev = (i - 1 + Main.images.length) % Main.images.length;
	var img1 = new Image();
	img1.src = Main.images[next].url;
	var img2 = new Image();
	img2.src = Main.images[prev].url;
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.images = [{ url : "img/artist.jpg", title : "Bailey and I welcome you to my portfolio"},{ url : "img/bailey-playing.jpg", title : "Bailey at Play"},{ url : "img/cheetah.jpg", title : "Cheetah"},{ url : "img/chimp.jpg", title : "Chimpanzee"},{ url : "img/elephant.jpg", title : "Elephant's Stare"},{ url : "img/elephant-2.jpg", title : "Elephant Running"},{ url : "img/giraffe.jpg", title : "Giraffe"},{ url : "img/lion.jpg", title : "Lion"},{ url : "img/rhino.jpg", title : "Rhino's Stare"},{ url : "img/rhino-2.jpg", title : "Rhino Running"},{ url : "img/tiger.jpg", title : "Friendly Tiger"},{ url : "img/tiger-2.jpg", title : "Fierce Tiger"}];
Main.index = 0;
Main.preloaded = [];
Main.touchStartX = 0;
Main.touchEndX = 0;
Main.touchStartTime = 0;
Main.touchEndTime = 0;
Main.minSwipeDistance = 40;
Main.minSwipeVelocity = 0.35;
Main.main();
})({});
